### ISSUE TITLE
Unhandled exception while processing import statement not in the module level

### ISSUE THREAD

**Issue by thisrabbit** [xjtu-enre/ENRE-py#11]
# Reproduction code

```py
class Bar:
    from foo import *
```

Wildcard import `from xxx import *` can only be used at the module level, that is to say, a `SyntaxException` will be thrown if developers try to use it within functions and classes.

# Expected

ENRE would actively detect this kind of error and print a message.

# What happened

An unhandled exception breaks ENRE:

```
Traceback (most recent call last):
  File "enre\__main__.py", line 72, in <module>
  File "enre\__main__.py", line 30, in main
  File "enre\__main__.py", line 44, in enre_wrapper
  File "enre\analysis\analyze_manager.py", line 151, in work_flow
  File "enre\analysis\analyze_manager.py", line 163, in iter_dir
  File "enre\analysis\analyze_manager.py", line 175, in iter_dir
  File "enre\analysis\analyze_stmt.py", line 395, in analyze_top_stmts
  File "enre\analysis\analyze_stmt.py", line 61, in analyze
  File "enre\analysis\analyze_stmt.py", line 172, in analyze_ClassDef
  File "enre\analysis\analyze_stmt.py", line 395, in analyze_top_stmts
  File "enre\analysis\analyze_stmt.py", line 61, in analyze
  File "enre\analysis\analyze_stmt.py", line 294, in analyze_ImportFrom
  File "enre\analysis\analyze_manager.py", line 186, in import_module
  File "enre\analysis\analyze_manager.py", line 106, in get_path_ent
KeyError: WindowsPath('<module path>') // The module path, in the upper case, foo
[8276] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by thisrabbit** [comment]
Understand does not treat this case as a syntax error, which results in the following code to be analyzed without throwing any errors:

```py
class Bar:
  from Foo import *  # Assume the module Foo contains a function named foo
  
  def bar(self):
    foo()  # Understand establishes a dependency of bar -call->foo, however this code is invalid and cannot really be executed
```
